version: "2.0"
services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - data:/data 
    environment:
      -  NEO4J_AUTH=neo4j/kali1sth#best
      -  NEO4J_dbms_memory_heap_max__size=512M
      -  NEO4J_dbms_memory_pagecache_size=512M
      -  NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
volumes:
  data:

networks:
  overlay:
